version: "3"
services:
  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py collectstatic --no-input --clear && gunicorn --workers 3  --bind  0.0.0.0:8000 project.wsgi:application"
    expose:
      - "8000"
    volumes:
      - static:/code/static_root
      - media:/code/media
    environment:
      - DJANGO_SETTINGS_MODULE=project.pro_settings
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        - AXIOS_BASEURL=http://backend:8000/api
        - AXIOS_BROWSER_BASEURL=/api
    expose:
      - "3000"
    command: "npm run start"
    environment:
      - AXIOS_BASEURL=http://backend:8000/api
      - AXIOS_BROWSER_BASEURL=/api

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "serenade-lg.com"
      STAGE: "production"
    volumes:
      - ./nginx_conf/serenade-lg.com.ssl.conf.erb:/var/lib/nginx-conf/serenade-lg.com.ssl.conf.erb:ro
      - static:/code/static_root
      - media:/code/media
    depends_on:
      - backend
      - frontend