# Generated by Django 3.2.14 on 2022-07-17 15:44

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='カテゴリー名')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像')),
                ('category', models.ManyToManyField(to='fashionItem.Category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=255, verbose_name='サブカテゴリー名')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionItem.category', verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#f4be9b', image_field=None, max_length=18, samples=None, verbose_name='色')),
                ('itemcount', models.IntegerField(default=0, verbose_name='商品数')),
                ('note', models.TextField(verbose_name='詳細説明')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionItem.item')),
            ],
        ),
    ]
