# Generated by Django 3.2.14 on 2022-07-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionItem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ManyToManyField(to='fashionItem.SubCategory', verbose_name='サブカテゴリー'),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fashionItem.item', verbose_name='アイテム'),
        ),
    ]
